#!/usr/bin/env python3
"""Deterministically map a generation target asset type to a callable route."""
import argparse, json, sys

EXACT={
 'CHARACTER_MASTER':'CHARACTER_MASTER','CHARACTER_DETAIL':'CHARACTER_MASTER','FUNCTIONAL_MINOR_HUMAN_ASSET':'FUNCTIONAL_MINOR_HUMAN_MASTER','MINOR_HUMAN_MASTER':'FUNCTIONAL_MINOR_HUMAN_MASTER',
 'EMPTY_ENVIRONMENT_MASTER':'ENVIRONMENT_MASTER_COVERAGE','ENVIRONMENT_CLEAN_CANON':'ENVIRONMENT_MASTER_COVERAGE','ENV_CANON_MASTER':'ENVIRONMENT_MASTER_COVERAGE',
 'SCENE_COLOR_EXTENSION_CARD':'SCENE_COLOR_CARD_DERIVATION','SCENE_COLOR_CARD':'SCENE_COLOR_CARD_DERIVATION',
 'GLOBAL_COLOR_CARD':'SCENE_COLOR_CARD_DERIVATION','BASE_COLOR_CARD':'SCENE_COLOR_CARD_DERIVATION',
 'PRODUCTION_SUPPORT_REFERENCE':'PRODUCTION_SUPPORT_REFERENCE','PERFORMANCE_EXPRESSION_SUPPORT':'PERFORMANCE_SUPPORT_ASSET','PERFORMANCE_ACTION_POSE_SUPPORT':'PERFORMANCE_SUPPORT_ASSET','PERFORMANCE_CONTACT_POSE_SUPPORT':'PERFORMANCE_SUPPORT_ASSET','NARRATIVE_FX_REFERENCE':'NARRATIVE_FX_ASSET','NARRATIVE_FX_STATE_SHEET':'NARRATIVE_FX_ASSET','SHOT_ASSEMBLY_ASSET':'SHOT_ASSEMBLY_ASSET','HD_SHOT_ASSEMBLY_IMAGE':'SHOT_ASSEMBLY_ASSET',
 'TRANSFORMATION_MASTER':'TRANSFORMATION_FIRST_DESIGN','TRANSFORMATION_FIRST_DESIGN':'TRANSFORMATION_FIRST_DESIGN','TRANSFORMATION_REPEAT':'TRANSFORMATION_REPEAT',
 'SHOT_EXECUTION_FRAME':'STAGE_04_VIDEO_CONDITIONING_BUILD','PRIMARY_VISUAL_CONDITIONING':'STAGE_04_VIDEO_CONDITIONING_BUILD',
 'VIDEO_SHOT_EXECUTION_FRAME':'STAGE_04_VIDEO_CONDITIONING_BUILD','VIDEO_FIRST_FRAME':'STAGE_04_VIDEO_CONDITIONING_BUILD','VIDEO_TARGET_FRAME':'STAGE_04_VIDEO_CONDITIONING_BUILD','VIDEO_LAST_FRAME':'STAGE_04_VIDEO_CONDITIONING_BUILD','VIDEO_CONTACT_FRAME':'STAGE_04_VIDEO_CONDITIONING_BUILD','VIDEO_KEY_POSE':'STAGE_04_VIDEO_CONDITIONING_BUILD',
 'VIDEO_TAKE':'STAGE_05_VIDEO','VIDEO_CLIP':'STAGE_05_VIDEO','FINAL_VIDEO_TAKE':'STAGE_05_VIDEO','VIDEO_SEGMENT':'STAGE_05_VIDEO',
 'CLEAN_STRUCTURAL_STORYBOARD':'STAGE_04_STORYBOARD','CLEAN_STORYBOARD_PANEL':'STAGE_04_STORYBOARD','STORYBOARD_CLEAN_PANEL':'STAGE_04_STORYBOARD','STORYBOARD_CONTACT_SHEET':'STAGE_04_STORYBOARD','STORYBOARD':'STAGE_04_STORYBOARD',
 'ACTION_CONTACT_KEY_POSE_CHAIN':'STAGE_04_STORYBOARD','SPATIAL_BLOCKING_MAP':'STAGE_04_STORYBOARD','CAMERA_PATH_PREVIS':'STAGE_04_STORYBOARD'
}
def resolve(asset_type:str)->str:
    t=asset_type.strip().upper()
    if t in EXACT: return EXACT[t]
    if t.startswith('VIDEO_'):
        return 'STAGE_04_VIDEO_CONDITIONING_BUILD' if 'FRAME' in t or 'POSE' in t else 'STAGE_05_VIDEO'
    if 'ENVIRONMENT' in t or t in {'EVENT_NODE_VIEW','RECIPROCAL_COVERAGE','RECIPROCAL_COVERAGE_VIEW','PREDICTIVE_COVERAGE','PREDICTIVE_COVERAGE_VIEW','SCENE_CLUE_VIEW'}: return 'ENVIRONMENT_MASTER_COVERAGE'
    if t.startswith('PROP_') or 'PROP' in t: return 'PROP_MASTER_COVERAGE'
    if 'TRANSFORMATION' in t: return 'TRANSFORMATION_FIRST_DESIGN'
    if 'CHARACTER' in t or t.startswith('FMH_'): return 'CHARACTER_MASTER'
    if 'NARRATIVE_FX' in t: return 'NARRATIVE_FX_ASSET'
    if t.startswith('PERFORMANCE_') and 'SUPPORT' in t: return 'PERFORMANCE_SUPPORT_ASSET'
    if 'ASSEMBLY' in t: return 'SHOT_ASSEMBLY_ASSET'
    if 'SUPPORT' in t: return 'PRODUCTION_SUPPORT_REFERENCE'
    raise ValueError(f'UNMAPPED_ASSET_TYPE:{asset_type}')
def main():
    ap=argparse.ArgumentParser(); ap.add_argument('asset_type'); ap.add_argument('--json',action='store_true'); a=ap.parse_args()
    try: out={'asset_type':a.asset_type,'route':resolve(a.asset_type),'pass':True}
    except ValueError as e:
        out={'asset_type':a.asset_type,'route':None,'pass':False,'error':str(e)}
        print(json.dumps(out,ensure_ascii=False,indent=2) if a.json else out['error'],file=sys.stdout if a.json else sys.stderr); return 2
    print(json.dumps(out,ensure_ascii=False,indent=2) if a.json else out['route']); return 0
if __name__=='__main__': raise SystemExit(main())
